# Generated by Django 3.2.15 on 2022-12-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_scenario_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('units', models.CharField(choices=[('kWh', 'kWh'), ('MWh', 'MWh')], max_length=50)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
