# Generated by Django 4.2.4 on 2024-10-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0019_timeseries")]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="input_timeseries",
            new_name="input_timeseries_old",
        )
    ]
