# Generated by Django 4.2.4 on 2025-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_migrate_timeseries_to_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionlink",
            name="asset_connection_port",
            field=models.CharField(default="no_mapping", max_length=12),
        ),
    ]
