# Generated by Django 4.2.4 on 2025-09-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_connectionlink_asset_connection_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionPort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.PositiveSmallIntegerField(help_text="Port number (0 … n)"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("input", "Asset Input"), ("output", "Asset Output")],
                        help_text="Input or output",
                        max_length=6,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. name of attribute of facade", max_length=60
                    ),
                ),
                (
                    "energy_vector",
                    models.CharField(
                        choices=[
                            ("", "Choose..."),
                            ("Electricity", "Electricity"),
                            ("Heat", "Heat"),
                            ("Gas", "Gas"),
                            ("H2", "H2"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="projects.assettype",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_type", "direction", "num"],
                "unique_together": {("asset_type", "direction", "num")},
            },
        ),
    ]
