# Generated by Django 4.2.4 on 2025-10-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_connectionport"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseries",
            name="component",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pv", "Photovoltaic"),
                    ("wind", "Wind"),
                    ("electricity_demand", "Electricity"),
                    ("heat_demand", "Heat"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeseries",
                to="projects.project",
            ),
        ),
    ]
