# Generated by Django 4.2.4 on 2025-09-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_connectionport"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionport",
            name="energy_vector",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Electricity", "Electricity"),
                    ("Heat", "Heat"),
                    ("Gas", "Gas"),
                    ("H2", "H2"),
                ],
                default="Merde",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectionport",
            name="label",
            field=models.CharField(
                help_text="e.g. name of attribute of facade", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="connectionport",
            name="num",
            field=models.PositiveSmallIntegerField(help_text="Port number (0 … n)"),
        ),
    ]
