# Generated by Django 4.2.4 on 2025-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_timeseries_component_timeseries_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeseries",
            name="component",
        ),
        migrations.RemoveField(
            model_name="timeseries",
            name="project",
        ),
        migrations.AddField(
            model_name="timeseries",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("demand", "demand"),
                    ("gas_demand", "gas_demand"),
                    ("h2_demand", "h2_demand"),
                    ("heat_demand", "heat_demand"),
                    ("pv_plant", "pv_plant"),
                    ("wind_plant", "wind_plant"),
                    ("biogas_plant", "biogas_plant"),
                    ("geothermal_conversion", "geothermal_conversion"),
                    ("solar_thermal_plant", "solar_thermal_plant"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
