# Generated by Django 5.2.13 on 2026-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_assign_timeseries_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensitivityanalysis",
            name="server",
            field=models.CharField(
                choices=[("MVS", "MVS"), ("EZP", "EZP")], default="MVS", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="server",
            field=models.CharField(
                choices=[("MVS", "MVS"), ("EZP", "EZP")], default="MVS", max_length=3
            ),
        ),
    ]
