# Generated by Django 5.2.13 on 2026-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_sensitivityanalysis_server_simulation_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="datapackage",
            field=models.JSONField(null=True),
        ),
    ]
