# Generated by Django 5.2.13 on 2026-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_sensitivityanalysis_server_simulation_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='generation_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
