# Generated by Django 5.2.13 on 2026-07-08 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_sensitivityanalysis_server_simulation_server"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                (
                    "full_load_hours_max",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "commodity_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
        migrations.AddField(
            model_name="asset",
            name="full_load_hours_max_asset",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
