# Generated by Django 5.2.13 on 2026-07-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_commodity_asset_full_load_hours_max_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
