# Generated by Django 5.2.13 on 2026-07-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricalStorage",
            fields=[
                (
                    "storage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.storage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.storage",),
        ),
        migrations.CreateModel(
            name="FuelStorage",
            fields=[
                (
                    "storage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.storage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.storage",),
        ),
        migrations.CreateModel(
            name="HydrogenStorage",
            fields=[
                (
                    "storage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.storage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.storage",),
        ),
        migrations.CreateModel(
            name="ThermalStorage",
            fields=[
                (
                    "storage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.storage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.storage",),
        ),
    ]
