# Generated by Django 5.2.13 on 2026-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_simulation_dp_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='figures',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
