# Generated by Django 5.2.13 on 2026-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_chp_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chp",
            name="conversion_factor_to_electricity",
            field=models.TextField(null=True),
        ),
    ]
