# Generated by Django 5.2.13 on 2026-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_chp_conversion_factor_to_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chp',
            name='conversion_factor_to_heat',
            field=models.TextField(null=True),
        ),
    ]
