# Generated by Django 5.2.13 on 2026-07-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_chp_fixed_ratio_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatPump",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                ("cop", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
