# Generated by Django 5.2.13 on 2026-07-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_electrolyzer_data_migration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="energy_price",
            new_name="energy_price_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="feedin_cap",
            new_name="feedin_cap_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="feedin_tariff",
            new_name="feedin_tariff_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="peak_demand_pricing",
            new_name="peak_demand_pricing_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="peak_demand_pricing_period",
            new_name="peak_demand_pricing_period_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="renewable_share",
            new_name="renewable_share_asset",
        ),
    ]
