# Generated by Django 5.2.13 on 2026-07-27 23:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_rename_energy_price_asset_energy_price_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSO",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                ("energy_price", models.TextField(null=True)),
                ("feedin_tariff", models.TextField(null=True)),
                (
                    "feedin_cap",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "peak_demand_pricing",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "peak_demand_pricing_period",
                    models.SmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (12, 12)],
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "renewable_share",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "energy_vector",
                    models.CharField(
                        choices=[
                            ("", "Choose..."),
                            ("Electricity", "Electricity"),
                            ("Heat", "Heat"),
                            ("Gas", "Gas"),
                            ("H2", "H2"),
                        ],
                        default="electricity",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
