# Generated by Django 5.2.13 on 2026-07-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_dso_data_migration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="crate",
            new_name="crate_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="fixed_thermal_losses_absolute",
            new_name="fixed_thermal_losses_absoluteA",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="fixed_thermal_losses_relative",
            new_name="fixed_thermal_losses_relativeA",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="soc_max",
            new_name="soc_max_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="soc_min",
            new_name="soc_min_asset",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="thermal_loss_rate",
            new_name="thermal_loss_rate_asset",
        ),
    ]
