# Generated by Django 5.2.13 on 2026-09-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_storage_data_migration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="capex_var",
            new_name="capex_spec",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="opex_fix",
            new_name="opex_spec",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="opex_var",
            new_name="variable_costs",
        ),
    ]
