# Generated by Django 5.2.13 on 2026-09-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_rename_capex_var_asset_capex_spec_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electricalstorage",
            old_name="crate",
            new_name="c_rate_charge",
        ),
        migrations.RenameField(
            model_name="fuelstorage",
            old_name="crate",
            new_name="c_rate_charge",
        ),
        migrations.RenameField(
            model_name="hydrogenstorage",
            old_name="crate",
            new_name="c_rate_charge",
        ),
        migrations.RenameField(
            model_name="thermalstorage",
            old_name="crate",
            new_name="c_rate_charge",
        ),
    ]
