# Generated by Django 5.2.13 on 2026-09-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0047_rename_fixed_thermal_losses_relative_thermalstorage_thermal_losses_fixed_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="chpfixedratio",
            old_name="conversion_factor_to_electricity",
            new_name="efficiency_electricity_chp",
        ),
        migrations.RenameField(
            model_name="chpfixedratio",
            old_name="conversion_factor_to_heat",
            new_name="efficiency_heat_chp",
        ),
    ]
