# Generated by Django 5.2.13 on 2026-09-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0048_rename_conversion_factor_to_electricity_chpfixedratio_efficiency_electricity_chp_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="chp",
            old_name="conversion_factor_to_electricity",
            new_name="efficiency_electricity_chp",
        ),
        migrations.RenameField(
            model_name="chp",
            old_name="beta",
            new_name="efficiency_electricity_full_condensation",
        ),
        migrations.RenameField(
            model_name="chp",
            old_name="conversion_factor_to_heat",
            new_name="efficiency_heat_chp",
        ),
    ]
