# Generated by Django 5.2.13 on 2026-09-29 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0049_rename_conversion_factor_to_electricity_chp_efficiency_electricity_chp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="electricalstorage",
            name="end_storage_level",
            field=models.BooleanField(
                blank=True, choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
        migrations.AddField(
            model_name="electricalstorage",
            name="initial_storage_level",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
