# Generated by Django 5.2.13 on 2026-09-29 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_electricalstorage_end_storage_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thermalstorage",
            name="end_storage_level",
            field=models.BooleanField(
                blank=True, choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
        migrations.AddField(
            model_name="thermalstorage",
            name="initial_storage_level",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
