# Generated by Django 5.2.13 on 2026-09-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_thermalstorage_end_storage_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalstorage",
            name="end_storage_level",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                verbose_name="Balance end storage level",
            ),
        ),
        migrations.AlterField(
            model_name="thermalstorage",
            name="end_storage_level",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                verbose_name="Balance end storage level",
            ),
        ),
    ]
