# Generated by Django 5.2.13 on 2026-09-30 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_alter_electricalstorage_end_storage_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatingPipe",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                ("absolute_losses", models.FloatField(blank=True, null=True)),
                (
                    "relative_losses",
                    models.FloatField(
                        default=0.0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "return_pipe",
                    models.BooleanField(
                        blank=True, choices=[(True, "Yes"), (False, "No")], default=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
