# Generated by Django 5.2.13 on 2026-10-01 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_heatingpipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatingNetwork",
            fields=[
                (
                    "bus_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.bus",
                    ),
                ),
                ("absolute_losses", models.TextField(null=True)),
                (
                    "unique_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=120, unique=True
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.assettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.bus",),
        ),
    ]
