# Generated by Django 5.2.13 on 2026-10-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_heatingnetwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sink",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                ("minimum", models.TextField(default=0)),
                ("maximum", models.TextField(default=1)),
                ("fix", models.TextField(blank=True, null=True)),
                ("positive_gradient_limit", models.FloatField(blank=True, null=True)),
                ("negative_gradient_limit", models.FloatField(blank=True, null=True)),
                ("full_load_time_max", models.FloatField(blank=True, null=True)),
                ("full_load_time_min", models.FloatField(blank=True, null=True)),
                (
                    "integer",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "True"), (False, "False")],
                        default=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
