# Generated by Django 5.2.13 on 2026-10-07 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_sink"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuxiliaryHeat",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.asset",
                    ),
                ),
                ("temp_in_heat", models.TextField(null=True)),
                ("temp_out_heat", models.TextField(null=True)),
                ("temp_low_source_component", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.asset",),
        ),
    ]
