services:

  db_pg:
    image: postgres:14.3-alpine
    env_file:
      - .envs/db.postgres
    expose:
      - 5432

  app_pg:
    build:
      context: .
      args:
        BUILD_ENVIRONMENT: local
      dockerfile: ./app/compose/production/app_postgres/Dockerfile
    env_file:
      - .envs/epa.postgres
    expose:
      - 8000
    depends_on:
      - db_pg
