#!/bin/bash

set -o errexit
set -o nounset



until timeout 10 celery -A epa.celery_config inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'


exec celery \
    -A epa.celery_config \
    -b "${REDIS_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
