"""
Django settings for EPA project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import ssl

from celery.schedules import crontab
from django.contrib.messages import constants as messages
import environ
from pathlib import Path
import sys

# Version number -> gets updated by bump-my-version, do not touch manually
APP_VERSION_NUMBER = "2.1.1"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root dir is a parent directory
ROOT_DIR = environ.Path(__file__) - 2

# Read environment variables
env = environ.Env()

# Read .env file
# OS environment variables take precedence over variables from .env file
env.read_env(str(ROOT_DIR.path(".env")))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "cdn_static_root/"
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Resources dir (containing helper csv files)
RESOURCES_DIR = BASE_DIR / "resources"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
PROD_ENV = env.bool("PROD_ENV", default=False)

if DEBUG is True:
    STATICFILES_FINDERS.append("sass_processor.finders.CssFinder")
    SASS_PROCESSOR_ROOT = STATIC_ROOT
    SASS_PRECISION = 8
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "EPA_SECRET_KEY", default="v@p9^=@lc3#1u_xtx*^xhrv0l3li1(+8ik^k@g-_bzmexb0$7n"
)

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = env.list("TRUSTED_HOST", default=[])
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.forms",
    "users.apps.UsersConfig",
    "projects.apps.ProjectsConfig",
    "dashboard.apps.DashboardConfig",
    # 3rd Party
    "crispy_forms",
    "crispy_bootstrap4",
    "django_celery_beat",
]

if DEBUG is True:
    INSTALLED_APPS.append("sass_processor")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

ROOT_URLCONF = "epa.urls"

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

CRISPY_TEMPLATE_PACK = "bootstrap4"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "epa.context_processors.debug",
                "epa.context_processors.app_version",
            ]
        },
    }
]

WSGI_APPLICATION = "epa.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# SQLite does not support ArrayField, so PostgreSQL is needed as engine
DATABASES = {
    "default": {
        "ENGINE": env("SQL_ENGINE", default="django.db.backends.postgresql"),
        "NAME": env("SQL_DATABASE"),
        "USER": env("SQL_USER", default=None),
        "PASSWORD": env("SQL_PASSWORD", default=None),
        "HOST": env("SQL_HOST", default=None),
        "PORT": env.int("SQL_PORT", default=5432),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en"

LOCALE_PATHS = (BASE_DIR / "locale",)

LANGUAGES = [("de", "German"), ("en", "English")]

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = False

# Other configs

AUTH_USER_MODEL = "users.CustomUser"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "project_search"
LOGOUT_REDIRECT_URL = "home"

# Please note, we don't use Django's internal email system,
# we implement our own, using exchangelib
USE_EXCHANGE_EMAIL_BACKEND = env.bool("USE_EXCHANGE_EMAIL_BACKEND", default=True)

# The Exchange account which sends emails
EXCHANGE_ACCOUNT = env("EXCHANGE_ACCOUNT", default="dummy@dummy.com")
EXCHANGE_PW = env("EXCHANGE_PW", default="dummypw")
EXCHANGE_EMAIL = env("EXCHANGE_EMAIL", default="dummy@dummy.com")
EXCHANGE_SERVER = env("EXCHANGE_SERVER", default="dummy.com")
# Email addresses to which feedback emails will be sent
RECIPIENTS = env.list("RECIPIENTS", default=["dummy@dummy.com", "dummy2@dummy.com"])
EMAIL_SUBJECT_PREFIX = env("EMAIL_SUBJECT_PREFIX", default="[OpenPlan] ")

MESSAGE_TAGS = {
    messages.DEBUG: "alert-info",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

USE_PROXY = env.bool("USE_PROXY", default=True)
PROXY_ADDRESS_LINK = env("PROXY_ADDRESS", default="http://proxy:port")
PROXY_CONFIG = (
    ({"http://": PROXY_ADDRESS_LINK, "https://": PROXY_ADDRESS_LINK})
    if USE_PROXY
    else (dict())
)

# Server queue which will process the simulation, openplan for prod mvs version and "" (blank) for dev mvs version
MVS_API_QUEUE = env("MVS_API_QUEUE", default="openplan")

MVS_API_HOST = env("MVS_API_HOST", default="https://mvs-eland.rl-institut.de")
MVS_POST_URL = f"{MVS_API_HOST}/sendjson/{MVS_API_QUEUE}"
MVS_GET_URL = f"{MVS_API_HOST}/check/"
MVS_LP_FILE_URL = f"{MVS_API_HOST}/get_lp_file/"
MVS_SA_POST_URL = f"{MVS_API_HOST}/sendjson/openplan/sensitivity-analysis"
MVS_SA_GET_URL = f"{MVS_API_HOST}/check-sensitivity-analysis/"

# Allow iframes to show in page
X_FRAME_OPTIONS = "SAMEORIGIN"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dtlnm": {
            "format": "%(asctime)s - %(levelname)8s - %(name)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "info_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "django_epa_info.log",
            "formatter": "dtlnm",
        },
        "warnings_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": "django_epa_warning.log",
            "formatter": "dtlnm",
        },
        "console": {
            "level": "WARNING",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
        },
    },
    "loggers": {
        "": {
            "handlers": ["info_file", "warnings_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "asyncio": {"level": "WARNING"},
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}


if PROD_ENV:
    # SECURITY
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-ssl-redirect
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    # https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-secure
    SESSION_COOKIE_SECURE = True
    # https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-name
    SESSION_COOKIE_NAME = "__Secure-sessionid"
    # https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-secure
    CSRF_COOKIE_SECURE = True
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-hsts-seconds
    # TODO: set this to 60 seconds first and then to 518400 once you prove the former works
    SECURE_HSTS_SECONDS = env.int(
        "SECURE_HSTS_SECONDS",
        default=60,
    )
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-hsts-include-subdomains
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
        default=True,
    )
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-hsts-preload
    SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
    # https://docs.djangoproject.com/en/dev/ref/middleware/#x-content-type-options-nosniff
    SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
        "DJANGO_SECURE_CONTENT_TYPE_NOSNIFF",
        default=True,
    )


REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")
REDIS_SSL = REDIS_URL.startswith("rediss://")

# Celery
# ------------------------------------------------------------------------------
if USE_TZ:
    # https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-timezone
    CELERY_TIMEZONE = TIME_ZONE
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-broker_url
CELERY_BROKER_URL = REDIS_URL
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#redis-backend-use-ssl
CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE} if REDIS_SSL else None
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-result_backend
CELERY_RESULT_BACKEND = REDIS_URL
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#redis-backend-use-ssl
CELERY_REDIS_BACKEND_USE_SSL = CELERY_BROKER_USE_SSL
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#result-extended
CELERY_RESULT_EXTENDED = True
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#result-backend-always-retry
# https://github.com/celery/celery/pull/6122
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#result-backend-max-retries
CELERY_RESULT_BACKEND_MAX_RETRIES = 10
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-accept_content
CELERY_ACCEPT_CONTENT = ["json"]
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-task_serializer
CELERY_TASK_SERIALIZER = "json"
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-result_serializer
CELERY_RESULT_SERIALIZER = "json"
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#task-time-limit
CELERY_TASK_TIME_LIMIT = 5 * 60
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#task-soft-time-limit
CELERY_TASK_SOFT_TIME_LIMIT = 60
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#beat-scheduler
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#beat-schedule
CELERY_BEAT_SCHEDULE = {
    "check-simulation-objects": {
        "task": "projects.tasks.check_simulation_objects",
        "schedule": crontab(minute="*/1"),
    },
}
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-send-task-events
CELERY_WORKER_SEND_TASK_EVENTS = True
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-task_send_sent_event
CELERY_TASK_SEND_SENT_EVENT = True
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-hijack-root-logger
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
