#!/bin/bash
echo COLLECTSTATIC
python /src/manage.py collectstatic --noinput
echo PUBLICATIONS
mkdir /src/cdn_static_root/assets/publications
cp /var/publications/*.pdf /src/cdn_static_root/assets/publications/
echo MIGRATE
python /src/manage.py showmigrations
python /src/manage.py migrate
python /src/manage.py update_assettype
python /src/manage.py update_valuetype
python /src/manage.py compilemessages
#python /src/manage.py loaddata 'src/fixtures/multivector_fixture.json'
echo $(ls -L 1 --dirsfirst)
gunicorn epa.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout=120
