# Generated by Django 4.2.4 on 2025-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_new_result_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportitem",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("timeseries", "Timeseries graph"),
                    ("timeseries_stacked", "Stacked timeseries graph"),
                    ("capacities", "Installed and optimized capacities"),
                    ("bar", "Bar chart"),
                    ("costs", "Cost breakdown"),
                    ("pie", "Pie chart"),
                    ("load_duration", "Load duration curve"),
                    ("sankey", "Sankey diagram"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sensitivityanalysisgraph",
            name="y",
            field=models.CharField(
                choices=[
                    ("annual_total_flow", "Aggregated flow"),
                    (
                        "annuity_om",
                        "Annual operation, maintenance and dispatch expenses",
                    ),
                    ("annuity_total", "Annuity"),
                    ("average_flow", "Average flow"),
                    ("costs_cost_om", "Operation and maintenance costs"),
                    ("costs_dispatch", "Dispatch costs"),
                    ("costs_investment_over_lifetime", "Investment costs"),
                    ("flow", "Dispatch of an asset"),
                    (
                        "levelized_cost_of_energy_of_asset",
                        "Levelized cost of throughput",
                    ),
                    ("optimizedAddCap", "Optimal additional capacity"),
                    ("peak_flow", "Peak flow"),
                    ("replacement_costs_during_project_lifetime", "Replacement costs"),
                ],
                max_length=50,
            ),
        ),
    ]
